### ISSUE TITLE
Cannot execute code

### ISSUE THREAD

**Issue by FernandoJHO** [vipinkhushu/Hackerearth-SDK-PHP#4]
Hi, I'm using your code for connecting my web application to HackerEarth V3 API, however, every time I try to run code there's no output. Also, attribute 'compile_status' is setted to "Could not create compile log file for stdout" and attribute 'status' is setted to "CE". I wonder if this is an API bug or something like that?

**Comment by vipinkhushu** [comment]
Hey Fernando,
This error is thrown when you said an incorrect 'language' parameter. You can try attaching a .cpp file as changing 'language' parameter to 'CPP'  on examples/runsource.php, line 20 or examples/compilesource.php, line 18. 


PS: after you do the above mentioned, hackerearth api might throw compile time error for a error free code. There is some issue with the API, I have contacted hackerearth's API admin. I will update you as soon as they give any update.

**Comment by FernandoJHO** [comment]
Thank you for answering. Did you mean running a .cpp file?, I tried that and still got "CE" on 'status' attribute.

**Comment by iamsudip** [comment]
@FernandoJHO @vipinkhushu The issue has been fixed. Please go ahead, retry and confirm.

Edit: I'll suggest to use asynchronous method of the API, which is reliable and consistent.

**Comment by robertjuniorand** [comment]
Yes, thank you very much, it's 100% worked.

**Comment by FernandoJHO** [comment]
Thanks, it works fine now. I’ll try to use the asynchronous method.

**Comment by vipinkhushu** [comment]
Thanks for solving this issue! @iamsudip
